CRITICAL - 2020-11-20 13:40:07 --> Allowed memory size of 134217728 bytes exhausted (tried to allocate 50331656 bytes)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 13:40:42 --> 7 : Failed to connect to maps.googleapis.com port 443: Timed out
#0 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(821): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('7', 'Failed to conne...')
#1 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(449): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(158): CodeIgniter\HTTP\CURLRequest->send('GET', 'https://maps.go...')
#3 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(46): CodeIgniter\HTTP\CURLRequest->request('GET', 'https://maps.go...')
#4 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(153): App\Controllers\Admin\Driver->getShortestMap('3.580994,98.662...', Array, Array)
#5 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(319): App\Controllers\Admin\Driver->recursiveAddress('3.580994,98.662...', Array, Array, 0, 3600, 0, 6, Array, 0)
#6 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Admin\Driver->setDriver()
#7 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Driver))
#8 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\internal-nutrilo\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2020-11-20 13:42:40 --> Allowed memory size of 134217728 bytes exhausted (tried to allocate 50331656 bytes)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 14:06:16 --> Maximum execution time of 60 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 14:24:04 --> Maximum execution time of 60 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 14:25:04 --> Maximum execution time of 60 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 14:26:05 --> Maximum execution time of 60 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 14:28:29 --> Maximum execution time of 60 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 14:29:55 --> Maximum execution time of 60 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 14:35:22 --> Maximum execution time of 60 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 14:38:10 --> 7 : Failed to connect to maps.googleapis.com port 443: Timed out
#0 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(821): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('7', 'Failed to conne...')
#1 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(449): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(158): CodeIgniter\HTTP\CURLRequest->send('GET', 'https://maps.go...')
#3 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(46): CodeIgniter\HTTP\CURLRequest->request('GET', 'https://maps.go...')
#4 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(147): App\Controllers\Admin\Driver->getShortestMap('3.558715,98.629...', Array, Array)
#5 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(330): App\Controllers\Admin\Driver->recursiveAddress('3.558715,98.629...', Array, Array, 1090, 3600, 2, 6, Array, 0)
#6 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Admin\Driver->setDriver()
#7 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Driver))
#8 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\internal-nutrilo\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2020-11-20 15:07:05 --> Maximum execution time of 60 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 15:13:46 --> Maximum execution time of 60 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 15:16:21 --> Maximum execution time of 60 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 15:17:21 --> Maximum execution time of 60 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 15:25:50 --> Maximum execution time of 60 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 15:27:41 --> Maximum execution time of 60 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 15:43:56 --> 7 : Failed to connect to maps.googleapis.com port 443: Timed out
#0 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(821): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('7', 'Failed to conne...')
#1 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(449): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(158): CodeIgniter\HTTP\CURLRequest->send('GET', 'https://maps.go...')
#3 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(46): CodeIgniter\HTTP\CURLRequest->request('GET', 'https://maps.go...')
#4 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(117): App\Controllers\Admin\Driver->getShortestMap('3.555143,98.649...', Array, Array)
#5 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(318): App\Controllers\Admin\Driver->recursiveAddress('3.555143,98.649...', Array, Array, 3762, 3600, 4, 6, Array, 0, 0)
#6 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Admin\Driver->setDriver()
#7 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Driver))
#8 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\internal-nutrilo\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2020-11-20 15:59:49 --> Maximum execution time of 60 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 16:20:44 --> Maximum execution time of 60 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 16:21:53 --> A non-numeric value encountered
#0 C:\xampp\htdocs\internal-nutrilo\app\Views\Admin\Driver_view.php(60): CodeIgniter\Debug\Exceptions->errorHandler(2, 'A non-numeric v...', 'C:\\xampp\\htdocs...', 60, Array)
#1 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('Admin/Driver_vi...', Array, true)
#3 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(401): view('Admin/Driver_vi...', Array)
#4 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Admin\Driver->setDriver()
#5 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Driver))
#6 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\internal-nutrilo\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-11-20 16:23:27 --> 52 : Empty reply from server
#0 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(821): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('52', 'Empty reply fro...')
#1 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(449): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(158): CodeIgniter\HTTP\CURLRequest->send('GET', 'https://maps.go...')
#3 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(151): CodeIgniter\HTTP\CURLRequest->request('GET', 'https://maps.go...')
#4 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(322): App\Controllers\Admin\Driver->recursiveAddress('3.592226,98.674...', Array, Array, 626, 3600, 2, 6, Array, 0, 0)
#5 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Admin\Driver->setDriver()
#6 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Driver))
#7 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\internal-nutrilo\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-11-20 16:24:36 --> Maximum execution time of 60 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 16:28:14 --> A non-numeric value encountered
#0 C:\xampp\htdocs\internal-nutrilo\app\Views\Admin\Driver_view.php(60): CodeIgniter\Debug\Exceptions->errorHandler(2, 'A non-numeric v...', 'C:\\xampp\\htdocs...', 60, Array)
#1 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('Admin/Driver_vi...', Array, true)
#3 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(401): view('Admin/Driver_vi...', Array)
#4 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Admin\Driver->setDriver()
#5 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Driver))
#6 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\internal-nutrilo\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-11-20 17:51:52 --> syntax error, unexpected '}'
#0 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(869): class_exists('\\App\\Controller...', true)
#5 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(394): CodeIgniter\CodeIgniter->startController()
#6 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\internal-nutrilo\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-11-20 18:05:42 --> Argument 1 passed to CodeIgniter\Database\BaseBuilder::whereIn() must be of the type string or null, array given, called in C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Model.php on line 1818
#0 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Model.php(1818): CodeIgniter\Database\BaseBuilder->whereIn(Array)
#1 C:\xampp\htdocs\internal-nutrilo\app\Models\Admin\Catering_order_detail_model.php(84): CodeIgniter\Model->__call('whereIn', Array)
#2 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(412): App\Models\Admin\Catering_order_detail_model->getMultipleOrder('72,76,64,69,59,...')
#3 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Admin\Driver->deliveryRoute()
#4 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Driver))
#5 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\internal-nutrilo\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-11-20 18:06:13 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')'
#0 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Admi...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Admi...')
#3 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(411): spl_autoload_call('App\\Models\\Admi...')
#4 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Admin\Driver->deliveryRoute()
#5 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Driver))
#6 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\internal-nutrilo\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-11-20 18:07:19 --> syntax error, unexpected ')'
#0 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(869): class_exists('\\App\\Controller...', true)
#5 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(394): CodeIgniter\CodeIgniter->startController()
#6 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\internal-nutrilo\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-11-20 19:58:34 --> count(): Parameter must be an array or an object that implements Countable
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'count(): Parame...', 'C:\\xampp\\htdocs...', 71, Array)
#1 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(71): count(NULL)
#2 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(470): App\Controllers\Admin\Driver->recursiveAddress('3.580994,98.662...', Array, Array, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
#3 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Admin\Driver->deliveryRoute()
#4 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Driver))
#5 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\internal-nutrilo\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-11-20 20:01:18 --> Maximum execution time of 120 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 20:03:48 --> Maximum execution time of 120 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 20:05:48 --> Maximum execution time of 120 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 20:09:02 --> Maximum execution time of 120 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 20:11:02 --> Maximum execution time of 120 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-20 20:38:10 --> 7 : Failed to connect to maps.googleapis.com port 443: Timed out
#0 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(821): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('7', 'Failed to conne...')
#1 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(449): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(158): CodeIgniter\HTTP\CURLRequest->send('GET', 'https://maps.go...')
#3 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(413): CodeIgniter\HTTP\CURLRequest->request('GET', 'https://maps.go...')
#4 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(472): App\Controllers\Admin\Driver->recursiveAddress2('3.580994,98.662...', Array, Array, 0, 0)
#5 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Admin\Driver->deliveryRoute()
#6 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Driver))
#7 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\internal-nutrilo\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-11-20 21:14:00 --> 22 : The requested URL returned error: 400 Bad Request
#0 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(821): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(449): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(158): CodeIgniter\HTTP\CURLRequest->send('GET', 'https://maps.go...')
#3 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(436): CodeIgniter\HTTP\CURLRequest->request('GET', 'https://maps.go...')
#4 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(474): App\Controllers\Admin\Driver->getTimeDelivery('3.580994,98.662...', '3.5847916, 98.6...')
#5 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Admin\Driver->deliveryRoute()
#6 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Driver))
#7 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\internal-nutrilo\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-11-20 21:14:38 --> syntax error, unexpected 'print_r' (T_STRING)
#0 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(869): class_exists('\\App\\Controller...', true)
#5 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(394): CodeIgniter\CodeIgniter->startController()
#6 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\internal-nutrilo\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-11-20 21:14:45 --> 22 : The requested URL returned error: 400 Bad Request
#0 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(821): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(449): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(158): CodeIgniter\HTTP\CURLRequest->send('GET', 'https://maps.go...')
#3 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(436): CodeIgniter\HTTP\CURLRequest->request('GET', 'https://maps.go...')
#4 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(474): App\Controllers\Admin\Driver->getTimeDelivery('3.580994,98.662...', '3.5847916, 98.6...')
#5 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Admin\Driver->deliveryRoute()
#6 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Driver))
#7 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\internal-nutrilo\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-11-20 21:15:25 --> 22 : The requested URL returned error: 400 Bad Request
#0 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(821): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(449): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(158): CodeIgniter\HTTP\CURLRequest->send('GET', 'https://maps.go...')
#3 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(436): CodeIgniter\HTTP\CURLRequest->request('GET', 'https://maps.go...')
#4 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(474): App\Controllers\Admin\Driver->getTimeDelivery('3.580994,98.662...', '3.5847916, 98.6...')
#5 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Admin\Driver->deliveryRoute()
#6 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Driver))
#7 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\internal-nutrilo\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-11-20 21:16:01 --> 22 : The requested URL returned error: 400 Bad Request
#0 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(821): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(449): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(158): CodeIgniter\HTTP\CURLRequest->send('GET', 'https://maps.go...')
#3 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(436): CodeIgniter\HTTP\CURLRequest->request('GET', 'https://maps.go...')
#4 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(475): App\Controllers\Admin\Driver->getTimeDelivery('3.580994,98.662...', '3.5847916, 98.6...')
#5 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Admin\Driver->deliveryRoute()
#6 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Driver))
#7 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\internal-nutrilo\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-11-20 21:22:48 --> 22 : The requested URL returned error: 400 Bad Request
#0 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(821): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(449): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(158): CodeIgniter\HTTP\CURLRequest->send('GET', 'https://maps.go...')
#3 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(436): CodeIgniter\HTTP\CURLRequest->request('GET', 'https://maps.go...')
#4 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(478): App\Controllers\Admin\Driver->getTimeDelivery('3.5847916, 98.6...', '3.585245,98.703...')
#5 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Admin\Driver->deliveryRoute()
#6 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Driver))
#7 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\internal-nutrilo\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-11-20 21:53:03 --> syntax error, unexpected ';', expecting function (T_FUNCTION) or const (T_CONST)
#0 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(869): class_exists('\\App\\Controller...', true)
#5 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(394): CodeIgniter\CodeIgniter->startController()
#6 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\internal-nutrilo\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-11-20 22:38:46 --> 7 : Failed to connect to maps.googleapis.com port 443: Timed out
#0 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(821): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('7', 'Failed to conne...')
#1 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(449): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(158): CodeIgniter\HTTP\CURLRequest->send('GET', 'https://maps.go...')
#3 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(436): CodeIgniter\HTTP\CURLRequest->request('GET', 'https://maps.go...')
#4 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(478): App\Controllers\Admin\Driver->getTimeDelivery('3.580994,98.662...', '3.584618,98.672...')
#5 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Admin\Driver->deliveryRoute()
#6 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Driver))
#7 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\internal-nutrilo\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-11-20 23:26:48 --> 52 : Empty reply from server
#0 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(821): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('52', 'Empty reply fro...')
#1 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(449): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(158): CodeIgniter\HTTP\CURLRequest->send('GET', 'https://maps.go...')
#3 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(436): CodeIgniter\HTTP\CURLRequest->request('GET', 'https://maps.go...')
#4 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(478): App\Controllers\Admin\Driver->getTimeDelivery('3.592226,98.674...', '3.584527,98.691...')
#5 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Admin\Driver->deliveryRoute()
#6 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Driver))
#7 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\internal-nutrilo\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-11-20 23:27:16 --> 7 : Failed to connect to maps.googleapis.com port 443: Timed out
#0 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(821): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('7', 'Failed to conne...')
#1 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(449): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\HTTP\CURLRequest.php(158): CodeIgniter\HTTP\CURLRequest->send('GET', 'https://maps.go...')
#3 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(436): CodeIgniter\HTTP\CURLRequest->request('GET', 'https://maps.go...')
#4 C:\xampp\htdocs\internal-nutrilo\app\Controllers\Admin\Driver.php(478): App\Controllers\Admin\Driver->getTimeDelivery('3.580994,98.662...', '3.589318,98.677...')
#5 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Admin\Driver->deliveryRoute()
#6 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Driver))
#7 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\internal-nutrilo\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\internal-nutrilo\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
